<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('negaras')->insert([
            ['id' => 1, 'Nama' => 'Afganistan', 'Kode' => 'AF'],
            ['id' => 2, 'Nama' => 'Albania', 'Kode' => 'AL'],
            ['id' => 3, 'Nama' => 'Aljazair', 'Kode' => 'DZ'],
            ['id' => 4, 'Nama' => 'Andorra', 'Kode' => 'AD'],
            ['id' => 5, 'Nama' => 'Angola', 'Kode' => 'AO'],
            ['id' => 6, 'Nama' => 'Antigua dan Barbuda', 'Kode' => 'AG'],
            ['id' => 7, 'Nama' => 'Argentina', 'Kode' => 'AR'],
            ['id' => 8, 'Nama' => 'Armenia', 'Kode' => 'AM'],
            ['id' => 9, 'Nama' => 'Australia', 'Kode' => 'AU'],
            ['id' => 10, 'Nama' => 'Austria', 'Kode' => 'AT'],
            ['id' => 11, 'Nama' => 'Azerbaijan', 'Kode' => 'AZ'],
            ['id' => 12, 'Nama' => 'Bahama', 'Kode' => 'BS'],
            ['id' => 13, 'Nama' => 'Bahrain', 'Kode' => 'BH'],
            ['id' => 14, 'Nama' => 'Bangladesh', 'Kode' => 'BD'],
            ['id' => 15, 'Nama' => 'Barbados', 'Kode' => 'BB'],
            ['id' => 16, 'Nama' => 'Belarus', 'Kode' => 'BY'],
            ['id' => 17, 'Nama' => 'Belgia', 'Kode' => 'BE'],
            ['id' => 18, 'Nama' => 'Belize', 'Kode' => 'BZ'],
            ['id' => 19, 'Nama' => 'Benin', 'Kode' => 'BJ'],
            ['id' => 20, 'Nama' => 'Bhutan', 'Kode' => 'BT'],
            ['id' => 21, 'Nama' => 'Bolivia', 'Kode' => 'BO'],
            ['id' => 22, 'Nama' => 'Bosnia dan Herzegovina', 'Kode' => 'BA'],
            ['id' => 23, 'Nama' => 'Botswana', 'Kode' => 'BW'],
            ['id' => 24, 'Nama' => 'Brasil', 'Kode' => 'BR'],
            ['id' => 25, 'Nama' => 'Brunei Darussalam', 'Kode' => 'BN'],
            ['id' => 26, 'Nama' => 'Bulgaria', 'Kode' => 'BG'],
            ['id' => 27, 'Nama' => 'Burkina Faso', 'Kode' => 'BF'],
            ['id' => 28, 'Nama' => 'Burundi', 'Kode' => 'BI'],
            ['id' => 29, 'Nama' => 'Kamboja', 'Kode' => 'KH'],
            ['id' => 30, 'Nama' => 'Kamerun', 'Kode' => 'CM'],
            ['id' => 31, 'Nama' => 'Kanada', 'Kode' => 'CA'],
            ['id' => 32, 'Nama' => 'Tanjung Verde', 'Kode' => 'CV'],
            ['id' => 33, 'Nama' => 'Republik Afrika Tengah', 'Kode' => 'CF'],
            ['id' => 34, 'Nama' => 'Chad', 'Kode' => 'TD'],
            ['id' => 35, 'Nama' => 'Chili', 'Kode' => 'CL'],
            ['id' => 36, 'Nama' => 'Tiongkok', 'Kode' => 'CN'],
            ['id' => 37, 'Nama' => 'Kolombia', 'Kode' => 'CO'],
            ['id' => 38, 'Nama' => 'Komoro', 'Kode' => 'KM'],
            ['id' => 39, 'Nama' => 'Kongo', 'Kode' => 'CG'],
            ['id' => 40, 'Nama' => 'Kosta Rika', 'Kode' => 'CR'],
            ['id' => 41, 'Nama' => 'Kroasia', 'Kode' => 'HR'],
            ['id' => 42, 'Nama' => 'Kuba', 'Kode' => 'CU'],
            ['id' => 43, 'Nama' => 'Siprus', 'Kode' => 'CY'],
            ['id' => 44, 'Nama' => 'Republik Ceko', 'Kode' => 'CZ'],
            ['id' => 45, 'Nama' => 'Denmark', 'Kode' => 'DK'],
            ['id' => 46, 'Nama' => 'Djibouti', 'Kode' => 'DJ'],
            ['id' => 47, 'Nama' => 'Dominika', 'Kode' => 'DM'],
            ['id' => 48, 'Nama' => 'Republik Dominika', 'Kode' => 'DO'],
            ['id' => 49, 'Nama' => 'Ekuador', 'Kode' => 'EC'],
            ['id' => 50, 'Nama' => 'Mesir', 'Kode' => 'EG'],
            ['id' => 51, 'Nama' => 'El Salvador', 'Kode' => 'SV'],
            ['id' => 52, 'Nama' => 'Guinea Khatulistiwa', 'Kode' => 'GQ'],
            ['id' => 53, 'Nama' => 'Eritrea', 'Kode' => 'ER'],
            ['id' => 54, 'Nama' => 'Estonia', 'Kode' => 'EE'],
            ['id' => 55, 'Nama' => 'Eswatini', 'Kode' => 'SZ'],
            ['id' => 56, 'Nama' => 'Etiopia', 'Kode' => 'ET'],
            ['id' => 57, 'Nama' => 'Fiji', 'Kode' => 'FJ'],
            ['id' => 58, 'Nama' => 'Finlandia', 'Kode' => 'FI'],
            ['id' => 59, 'Nama' => 'Perancis', 'Kode' => 'FR'],
            ['id' => 60, 'Nama' => 'Gabon', 'Kode' => 'GA'],
            ['id' => 61, 'Nama' => 'Gambia', 'Kode' => 'GM'],
            ['id' => 62, 'Nama' => 'Georgia', 'Kode' => 'GE'],
            ['id' => 63, 'Nama' => 'Jerman', 'Kode' => 'DE'],
            ['id' => 64, 'Nama' => 'Ghana', 'Kode' => 'GH'],
            ['id' => 65, 'Nama' => 'Yunani', 'Kode' => 'GR'],
            ['id' => 66, 'Nama' => 'Grenada', 'Kode' => 'GD'],
            ['id' => 67, 'Nama' => 'Guatemala', 'Kode' => 'GT'],
            ['id' => 68, 'Nama' => 'Guinea', 'Kode' => 'GN'],
            ['id' => 69, 'Nama' => 'Guinea-Bissau', 'Kode' => 'GW'],
            ['id' => 70, 'Nama' => 'Guyana', 'Kode' => 'GY'],
            ['id' => 71, 'Nama' => 'Haiti', 'Kode' => 'HT'],
            ['id' => 72, 'Nama' => 'Honduras', 'Kode' => 'HN'],
            ['id' => 73, 'Nama' => 'Hungaria', 'Kode' => 'HU'],
            ['id' => 74, 'Nama' => 'Islandia', 'Kode' => 'IS'],
            ['id' => 75, 'Nama' => 'India', 'Kode' => 'IN'],
            ['id' => 76, 'Nama' => 'Indonesia', 'Kode' => 'ID'],
            ['id' => 77, 'Nama' => 'Iran', 'Kode' => 'IR'],
            ['id' => 78, 'Nama' => 'Irak', 'Kode' => 'IQ'],
            ['id' => 79, 'Nama' => 'Irlandia', 'Kode' => 'IE'],
            ['id' => 80, 'Nama' => 'Israel', 'Kode' => 'IL'],
            ['id' => 81, 'Nama' => 'Italia', 'Kode' => 'IT'],
            ['id' => 82, 'Nama' => 'Jamaika', 'Kode' => 'JM'],
            ['id' => 83, 'Nama' => 'Jepang', 'Kode' => 'JP'],
            ['id' => 84, 'Nama' => 'Yordania', 'Kode' => 'JO'],
            ['id' => 85, 'Nama' => 'Kazakhstan', 'Kode' => 'KZ'],
            ['id' => 86, 'Nama' => 'Kenya', 'Kode' => 'KE'],
            ['id' => 87, 'Nama' => 'Kiribati', 'Kode' => 'KI'],
            ['id' => 88, 'Nama' => 'Kuwait', 'Kode' => 'KW'],
            ['id' => 89, 'Nama' => 'Kirgizstan', 'Kode' => 'KG'],
            ['id' => 90, 'Nama' => 'Laos', 'Kode' => 'LA'],
            ['id' => 91, 'Nama' => 'Latvia', 'Kode' => 'LV'],
            ['id' => 92, 'Nama' => 'Lebanon', 'Kode' => 'LB'],
            ['id' => 93, 'Nama' => 'Lesotho', 'Kode' => 'LS'],
            ['id' => 94, 'Nama' => 'Liberia', 'Kode' => 'LR'],
            ['id' => 95, 'Nama' => 'Libya', 'Kode' => 'LY'],
            ['id' => 96, 'Nama' => 'Liechtenstein', 'Kode' => 'LI'],
            ['id' => 97, 'Nama' => 'Lituania', 'Kode' => 'LT'],
            ['id' => 98, 'Nama' => 'Luksemburg', 'Kode' => 'LU'],
            ['id' => 99, 'Nama' => 'Madagaskar', 'Kode' => 'MG'],
            ['id' => 100, 'Nama' => 'Malawi', 'Kode' => 'MW'],
            ['id' => 101, 'Nama' => 'Malaysia', 'Kode' => 'MY'],
            ['id' => 102, 'Nama' => 'Maladewa', 'Kode' => 'MV'],
            ['id' => 103, 'Nama' => 'Mali', 'Kode' => 'ML'],
            ['id' => 104, 'Nama' => 'Malta', 'Kode' => 'MT'],
            ['id' => 105, 'Nama' => 'Kepulauan Marshall', 'Kode' => 'MH'],
            ['id' => 106, 'Nama' => 'Mauritania', 'Kode' => 'MR'],
            ['id' => 107, 'Nama' => 'Mauritius', 'Kode' => 'MU'],
            ['id' => 108, 'Nama' => 'Meksiko', 'Kode' => 'MX'],
            ['id' => 109, 'Nama' => 'Mikronesia', 'Kode' => 'FM'],
            ['id' => 110, 'Nama' => 'Moldova', 'Kode' => 'MD'],
            ['id' => 111, 'Nama' => 'Monako', 'Kode' => 'MC'],
            ['id' => 112, 'Nama' => 'Mongolia', 'Kode' => 'MN'],
            ['id' => 113, 'Nama' => 'Montenegro', 'Kode' => 'ME'],
            ['id' => 114, 'Nama' => 'Maroko', 'Kode' => 'MA'],
            ['id' => 115, 'Nama' => 'Mozambik', 'Kode' => 'MZ'],
            ['id' => 116, 'Nama' => 'Myanmar', 'Kode' => 'MM'],
            ['id' => 117, 'Nama' => 'Namibia', 'Kode' => 'NA'],
            ['id' => 118, 'Nama' => 'Nauru', 'Kode' => 'NR'],
            ['id' => 119, 'Nama' => 'Nepal', 'Kode' => 'NP'],
            ['id' => 120, 'Nama' => 'Belanda', 'Kode' => 'NL'],
            ['id' => 121, 'Nama' => 'Selandia Baru', 'Kode' => 'NZ'],
            ['id' => 122, 'Nama' => 'Nikaragua', 'Kode' => 'NI'],
            ['id' => 123, 'Nama' => 'Niger', 'Kode' => 'NE'],
            ['id' => 124, 'Nama' => 'Nigeria', 'Kode' => 'NG'],
            ['id' => 125, 'Nama' => 'Korea Utara', 'Kode' => 'KP'],
            ['id' => 126, 'Nama' => 'Makedonia Utara', 'Kode' => 'MK'],
            ['id' => 127, 'Nama' => 'Norwegia', 'Kode' => 'NO'],
            ['id' => 128, 'Nama' => 'Oman', 'Kode' => 'OM'],
            ['id' => 129, 'Nama' => 'Pakistan', 'Kode' => 'PK'],
            ['id' => 130, 'Nama' => 'Palau', 'Kode' => 'PW'],
            ['id' => 131, 'Nama' => 'Panama', 'Kode' => 'PA'],
            ['id' => 132, 'Nama' => 'Papua Nugini', 'Kode' => 'PG'],
            ['id' => 133, 'Nama' => 'Paraguay', 'Kode' => 'PY'],
            ['id' => 134, 'Nama' => 'Peru', 'Kode' => 'PE'],
            ['id' => 135, 'Nama' => 'Filipina', 'Kode' => 'PH'],
            ['id' => 136, 'Nama' => 'Polandia', 'Kode' => 'PL'],
            ['id' => 137, 'Nama' => 'Portugal', 'Kode' => 'PT'],
            ['id' => 138, 'Nama' => 'Qatar', 'Kode' => 'QA'],
            ['id' => 139, 'Nama' => 'Rumania', 'Kode' => 'RO'],
            ['id' => 140, 'Nama' => 'Rusia', 'Kode' => 'RU'],
            ['id' => 141, 'Nama' => 'Rwanda', 'Kode' => 'RW'],
            ['id' => 142, 'Nama' => 'Saint Kitts dan Nevis', 'Kode' => 'KN'],
            ['id' => 143, 'Nama' => 'Saint Lucia', 'Kode' => 'LC'],
            ['id' => 144, 'Nama' => 'Saint Vincent dan Grenadines', 'Kode' => 'VC'],
            ['id' => 145, 'Nama' => 'Samoa', 'Kode' => 'WS'],
            ['id' => 146, 'Nama' => 'San Marino', 'Kode' => 'SM'],
            ['id' => 147, 'Nama' => 'Sao Tome dan Principe', 'Kode' => 'ST'],
            ['id' => 148, 'Nama' => 'Arab Saudi', 'Kode' => 'SA'],
            ['id' => 149, 'Nama' => 'Senegal', 'Kode' => 'SN'],
            ['id' => 150, 'Nama' => 'Serbia', 'Kode' => 'RS'],
            ['id' => 151, 'Nama' => 'Seychelles', 'Kode' => 'SC'],
            ['id' => 152, 'Nama' => 'Sierra Leone', 'Kode' => 'SL'],
            ['id' => 153, 'Nama' => 'Singapura', 'Kode' => 'SG'],
            ['id' => 154, 'Nama' => 'Slovakia', 'Kode' => 'SK'],
            ['id' => 155, 'Nama' => 'Slovenia', 'Kode' => 'SI'],
            ['id' => 156, 'Nama' => 'Kepulauan Solomon', 'Kode' => 'SB'],
            ['id' => 157, 'Nama' => 'Somalia', 'Kode' => 'SO'],
            ['id' => 158, 'Nama' => 'Afrika Selatan', 'Kode' => 'ZA'],
            ['id' => 159, 'Nama' => 'Korea Selatan', 'Kode' => 'KR'],
            ['id' => 160, 'Nama' => 'Sudan Selatan', 'Kode' => 'SS'],
            ['id' => 161, 'Nama' => 'Spanyol', 'Kode' => 'ES'],
            ['id' => 162, 'Nama' => 'Sri Lanka', 'Kode' => 'LK'],
            ['id' => 163, 'Nama' => 'Sudan', 'Kode' => 'SD'],
            ['id' => 164, 'Nama' => 'Suriname', 'Kode' => 'SR'],
            ['id' => 165, 'Nama' => 'Swedia', 'Kode' => 'SE'],
            ['id' => 166, 'Nama' => 'Swiss', 'Kode' => 'CH'],
            ['id' => 167, 'Nama' => 'Suriah', 'Kode' => 'SY'],
            ['id' => 168, 'Nama' => 'Taiwan', 'Kode' => 'TW'],
            ['id' => 169, 'Nama' => 'Tajikistan', 'Kode' => 'TJ'],
            ['id' => 170, 'Nama' => 'Tanzania', 'Kode' => 'TZ'],
            ['id' => 171, 'Nama' => 'Thailand', 'Kode' => 'TH'],
            ['id' => 172, 'Nama' => 'Timor Leste', 'Kode' => 'TL'],
            ['id' => 173, 'Nama' => 'Togo', 'Kode' => 'TG'],
            ['id' => 174, 'Nama' => 'Tonga', 'Kode' => 'TO'],
            ['id' => 175, 'Nama' => 'Trinidad dan Tobago', 'Kode' => 'TT'],
            ['id' => 176, 'Nama' => 'Tunisia', 'Kode' => 'TN'],
            ['id' => 177, 'Nama' => 'Turki', 'Kode' => 'TR'],
            ['id' => 178, 'Nama' => 'Turkmenistan', 'Kode' => 'TM'],
            ['id' => 179, 'Nama' => 'Tuvalu', 'Kode' => 'TV'],
            ['id' => 180, 'Nama' => 'Uganda', 'Kode' => 'UG'],
            ['id' => 181, 'Nama' => 'Ukraina', 'Kode' => 'UA'],
            ['id' => 182, 'Nama' => 'Uni Emirat Arab', 'Kode' => 'AE'],
            ['id' => 183, 'Nama' => 'Britania Raya', 'Kode' => 'GB'],
            ['id' => 184, 'Nama' => 'Amerika Serikat', 'Kode' => 'US'],
            ['id' => 185, 'Nama' => 'Uruguay', 'Kode' => 'UY'],
            ['id' => 186, 'Nama' => 'Uzbekistan', 'Kode' => 'UZ'],
            ['id' => 187, 'Nama' => 'Vanuatu', 'Kode' => 'VU'],
            ['id' => 188, 'Nama' => 'Kota Vatikan', 'Kode' => 'VA'],
            ['id' => 189, 'Nama' => 'Venezuela', 'Kode' => 'VE'],
            ['id' => 190, 'Nama' => 'Vietnam', 'Kode' => 'VN'],
            ['id' => 191, 'Nama' => 'Yaman', 'Kode' => 'YE'],
            ['id' => 192, 'Nama' => 'Zambia', 'Kode' => 'ZM'],
            ['id' => 193, 'Nama' => 'Zimbabwe', 'Kode' => 'ZW'],
            ['id' => 194, 'Nama' => 'Kosovo', 'Kode' => 'XK'],
            ['id' => 195, 'Nama' => 'Palestina', 'Kode' => 'PS'],
        ]);
    }
}
