<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MasterMerekSeeder extends Seeder
{
    public function run(): void
    {
        $merks = [
            'BTL',
            'PHILIPS',
            'HELENA',
            'ALIFAX',
            'ACCUCHECK',
            'SYSMEX',
            'COBAS',
            'QUANSTUDIO',
            'MPM',
            'AMBU',
            'GE',
            'DRAEGER',
            'ESCO',
            'R HAAG STREET',
            'INFAB',
            'LABOTECT',
            'SMITH & NEPHEW',
            'INTRACOUSTIC',
            'OSCILLA',
            'TOPCON',
            'HIRAYAMA',
            'GETTINGE',
            'STATIM',
            'KINGFISHER',
            'WELCH ALLYN',
            '3M',
            'RIGHTON',
            'SHIN NIPPON',
            'MAK',
            'PARAMOUNT',
            'GEA',
            'DRAEGER',
            'DAVID N',
            'SECALE',
            'ARNEZ',
            'SERENITYT',
            'PARAMOUNT',
            'CHINESPORT',
            'PARAMOUNT',
            'HOPEFULL',
            'INTERACCOUSTIC',
            'OLYMPUS',
            'HAIER',
            'HAIER',
            'TOMEY',
            'COVIDIEN',
            'SCI',
            'TERUMO',
            'HELMER',
            'CENTRONLLECTION',
            'LOCALT',
            'TANITAPOSITION',
            'ANALYZER',
            'ANALYZER RUIJINsaw',
            'CONMO',
            'FISHER & PAYKEL',
            'IKAGEMI',
            'DR OPPE',
            'MINDRAY',
            'CLEMENT',
            'EPENDORF',
            'NUVEGE',
            'THERMO SCIENTIFIC',
            'BIOBASE',
            'UNICOS',
            'ECLERIS',
            'SERENITY',
            'ICRO',
            'ANTECH',
            'ELLMAN',
            'KODAK',
            'CONECTO',
            'TAYLOR WARTHON',
            'TAYLOR WARTHONC',
            'LEICA',
            'SIEMENS',
            'GE',
            'INTEGRA',
            'RICHARD WOLF',
            'PHILIPS',
            'FENGDAN',
            'CUANGXIN',
            'SIRONA',
            'BELMONT',
            'HDY BESMENT',
            'BISTOS',
            'RADMEDIX',
            'FUJIFILM',
            'RAYENCE',
            'GE',
            'MINDRAY',
            'FUKUDA DENSHI',
            'CADWELL',
            'METRONIC',
            'VALLEYLAB',
            'HWATO',
            'BTL',
            'TRIMED',
            'METROLIFE',
            'MEGA MEDICAL',
            'EUROCLINIC',
            'REOCOR',
            'S DYNAMIC',
            'COMPACT 530',
            'SMITH MACHINE',
            'C & U',
            'HUMIDIFIER',
            'KOMATSU',
            'OXYVAC',
            'GEA',
            'SWITCHER',
            'GENOSE',
            'TERUMO',
            'FAMILY',
            'INFAB',
            'J % J',
            'MEBER',
            'Serenity',
            'RIESTER',
            'VERIMED',
            'CHINA BMC',
            'ARROW',
            'ROCHE',
            'HAEREUS',
            'DAVID N',
            'WARMER',
            'MEMMERT',
            'ZEISS',
            'RAYSHIELD',
            'ESCO',
            'URODYN',
            'SOGATA'
        ];

        $data = [];
        foreach ($merks as $merk) {
            $data[] = ['Nama' => $merk, 'UserCreate' => 'System', 'UserUpdate' => 'System'];
        }

        DB::table('master_merks')->insert($data);
    }
}
